#!/bin/bash

VERSION_FILE=".version_dev"
CURRENT_VERSION=$(cat $VERSION_FILE)

IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT_VERSION"

PATCH=$((PATCH + 1))
NEW_VERSION="$MAJOR.$MINOR.$PATCH"

echo "$NEW_VERSION" > $VERSION_FILE
echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
