name: Build and Push Docker Image (Dev)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

           - name: Generate version dynamically
        id: versioning
        run: |
          chmod +x ./version-dev.sh
          VERSION=$(./version-dev.sh)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "::set-output name=tag::$VERSION"


           - name: Build and push Docker image with dynamic version
  uses: docker/build-push-action@v5
  with:
    context: .
    push: true
    tags: sathish10162000/hello-docker-ci:${{ env.VERSION }}


