name: Build and Push Docker Image with Versioning

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: sathish10162000/hello-docker-ci

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make version script executable
        run: chmod +x version-dev.sh

      - name: Run version bump script
        id: version
        run: |
          ./version-dev.sh
          echo "VERSION=$(cat .version_dev)" >> $GITHUB_ENV

      - name: Commit updated version files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .version_dev .version_dev_date
          git commit -m "chore: update version files [skip ci]" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t ${{ env.IMAGE_NAME }}:${{ env.VERSION }} .
          docker push ${{ env.IMAGE_NAME }}:${{ env.VERSION }}
