name: Build and Push Docker Image (Dev)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Make version script executable and run it
        run: |
          chmod +x .github/scripts/version-dev.sh
          .github/scripts/version-dev.sh

      - name: Build and push Docker image with dynamic tag
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: sathish10162000/hello-docker-ci:${{ env.NEW_VERSION }}

      - name: Commit updated version files back to repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .version_dev .version_dev_date
          git commit -m "chore: update version to ${{ env.NEW_VERSION }} [skip ci]" || echo "No changes to commit"
          git push origin main || echo "Nothing to push"
