name: Dev Deployment

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: hello-docker-ci

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make version script executable
        run: chmod +x version-dev.sh

      - name: Setup versioning
        run: ./version-dev.sh

     - name: Push updated version to repo
       run: |
       git config --global user.email "github-actions@github.com"
       git config --global user.name "github-actions"
       git remote set-url origin https://x-access-token:${{ secrets.REPO_PAT }}@github.com/${{ github.repository }}
       git add .version_dev .version_dev_date
       git commit -m "chore: update version files [skip ci]" || echo "No changes to commit"
       git push origin main



      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}
          tags: type=raw,value=${{ env.NEW_VERSION }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}

