
name: Build and Push Docker Image with Version

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
           - name: Checkout code
        uses: actions/checkout@v3

      - name: Make version script executable
        run: chmod +x .github/scripts/version-bump.sh

      - name: Run version bump script
        id: bump
        run: .github/scripts/version-bump.sh


      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/your-repo:${{ steps.bump.outputs.new_version }}

      - name: Commit updated version
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .version
          git commit -m "ci: bump version to ${{ steps.bump.outputs.new_version }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

